import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

// html 문서 head 태그 title, description 설정
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: 'Next.js, React, Web Development',
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};
